<?php
/**
 * @file
 * resources_features.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function resources_features_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'resources_by_term';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Resources by term';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Resources by term';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'mini';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'node';
  $handler->display->display_options['row_options']['view_mode'] = 'full';
  $handler->display->display_options['row_options']['links'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Sort criterion: Content: Sticky */
  $handler->display->display_options['sorts']['sticky']['id'] = 'sticky';
  $handler->display->display_options['sorts']['sticky']['table'] = 'node';
  $handler->display->display_options['sorts']['sticky']['field'] = 'sticky';
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Contextual filter: Content: Category (field_resource_category) */
  $handler->display->display_options['arguments']['field_resource_category_tid']['id'] = 'field_resource_category_tid';
  $handler->display->display_options['arguments']['field_resource_category_tid']['table'] = 'field_data_field_resource_category';
  $handler->display->display_options['arguments']['field_resource_category_tid']['field'] = 'field_resource_category_tid';
  $handler->display->display_options['arguments']['field_resource_category_tid']['default_action'] = 'not found';
  $handler->display->display_options['arguments']['field_resource_category_tid']['default_argument_type'] = 'fixed';
  $handler->display->display_options['arguments']['field_resource_category_tid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_resource_category_tid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_resource_category_tid']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_resource_category_tid']['specify_validation'] = TRUE;
  $handler->display->display_options['arguments']['field_resource_category_tid']['validate']['type'] = 'taxonomy_term';
  $handler->display->display_options['arguments']['field_resource_category_tid']['validate_options']['vocabularies'] = array(
    'resource_category' => 'resource_category',
  );
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'resource' => 'resource',
  );

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block');
  $export['resources_by_term'] = $view;

  return $export;
}
