<?php

/**
 * Implements hook_menu().
 */
function sixeight_admin_menu() {
  $items['admin/config/sixeight'] = array(
    'title' => 'Six:Eight',
    'description' => 'Configure Six:Eight specific settings.',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  // admin/config/sixeight/order/system-order
  $items['admin/config/sixeight/order'] = array(
    'title' => 'Six:Eight Ordering',
    'description' => 'Order Six:Eight items.',
    'position' => 'left',
    'page callback' => 'sixeight_admin_order_landing_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
/*
  $items['admin/config/sixeight/order/system-order'] = array(
    'title' => 'Six:Eight - Ordering',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/sixeight/order/cg-order'] = array(
    'title' => 'Six:Eight - Ordering',
    'type' => MENU_LOCAL_TASK,
  );
*/
  return $items;
}

function sixeight_admin_order_landing_page() {
  return 'Order different items on the site.';
}

/**
 * Implements hook_permission().
 */
function sixeight_admin_permission() {
  return array(
    'administer sixeight' => array(
      'title' => t('Administer Six:Eight settings'),
      'description' => t('Perform administration tasks for Six:Eight.'),
    ),
  );
}
