<?php

/**
 * Implements hook_menu().
 */
function sixeight_admin_menu() {
  $items['admin/config/sixeight'] = array(
    'title' => 'Six:Eight',
    'description' => 'Configure Six:Eight specific settings.',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  // admin/config/sixeight/order/system-order
  $items['admin/config/sixeight/order'] = array(
    'title' => 'Six:Eight Ordering',
    'description' => 'Order Six:Eight items.',
    'position' => 'left',
    'page callback' => 'sixeight_admin_order_landing_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Overflow Files
  $items['system/overflow'] = array(
    'title' => 'overflow files',
    'page callback' => 'file_download',
    'page arguments' => array('overflow'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['system/overflow/styles/%image_style'] = array(
    'title' => 'Generate image style',
    'page callback' => 'image_style_deliver',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function sixeight_admin_menu_alter(&$items) {
  $items['node/%node']['page callback'] = 'sixeight_admin_node_page_view';
}

/**
 *  Redirect certain nodes to other pages.
 */
function sixeight_admin_node_page_view($node) {

  switch ($node->type) {
  case 'resource':
    drupal_goto('resources/other-resources', array('fragment' => 'node-' . $node->nid));
    break;
  case 'sermon':
    $sermons_per_page = 10;
    $all_sermons = views_get_view_result('sermons', 'totals');

    foreach ($all_sermons as $i => $sermon) {
      if ($sermon->nid == $node->nid) {
        $page = floor($i / $sermons_per_page);
        break;
      }
    }

    drupal_goto('resources/sermons', array('fragment' => 'node-' . $node->nid, 'query' => array('page' => $page)));
    break;
  case 'sermon_series':
    drupal_goto('resources/sermons', array('query' => array('field_sermon_series_target_id' => $node->nid)));
    break;
  case 'person':
    drupal_goto('people');
    break;
  case 'community_group':
    drupal_goto('connect/community-groups');
    break;
  }

  return node_page_view($node);
}

function sixeight_admin_order_landing_page() {
  return 'Order different items on the site.';
}

/**
 * Implements hook_permission().
 */
function sixeight_admin_permission() {
  return array(
    'administer sixeight' => array(
      'title' => t('Administer Six:Eight settings'),
      'description' => t('Perform administration tasks for Six:Eight.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function sixeight_admin_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {
  case 'views_exposed_form':
    switch ($form_state['view']->name) {
    case 'sermons':

      $field = 'field_speaker';
      $q = db_select('field_data_' . $field, 'f')
        ->fields('n', array('nid', 'title'));
      $q->join('node', 'n', 'f.'.$field.'_target_id = n.nid');

      $r = $q->execute();

      $form[$field . '_target_id']['#options'][''] = '-Any-';
      while ($row = $r->fetchAssoc() ) {
        $form[$field . '_target_id']['#options'][$row['nid']] = $row['title'];
      }

      $form[$field . '_target_id']['#type'] = 'select';
      unset($form[$field . '_target_id']['#size']);


      //Sermon Series
      $field = 'field_sermon_series';
      $q = db_select('field_data_' . $field, 'f')
        ->fields('n', array('nid', 'title'));
      $q->join('node', 'n', 'f.'.$field.'_target_id = n.nid');

      $r = $q->execute();

      $form[$field . '_target_id']['#options'][''] = '-Any-';
      while ($row = $r->fetchAssoc() ) {
        $form[$field . '_target_id']['#options'][$row['nid']] = $row['title'];
      }

      $form[$field . '_target_id']['#type'] = 'select';
      unset($form[$field . '_target_id']['#size']);


      break;
    }
    break;
  }
}



/**
 * Implements hook_stream_wrappers().
 */
function sixeight_admin_stream_wrappers() {
  return array(
    'overflow' => array(
      'name' => t('Overflow Files'),
      'class' => 'OverflowPublicStreamWrapper',
      'description' => t('Public local files served by the webserver on overflow drive.'),
      'type' => STREAM_WRAPPERS_LOCAL_NORMAL,
    ),
  );
}

class OverflowPublicStreamWrapper extends DrupalLocalStreamWrapper {
  public function getDirectoryPath() {
    return '/mnt/overflow/sixeight';
  }

  public function getExternalUrl() {
    $path = str_replace('\\', '/', $this->getTarget());
    return url('system/overflow/' . drupal_encode_path($path), array('absolute' => TRUE));
  }
}

function sixeight_admin_views_ajax_data_alter(&$commands, $view) {
  $commands[] = ajax_command_prepend($commands[0]['selector'], theme('status_messages'));
}

/**
 * Implements hook_entity_info_alter().
 */
function sixeight_admin_entity_info_alter(&$entity_info) {

  $entity_info['node']['view modes']['sixeight_admin_front_page_block'] = array(
    'label' => t('Front Page Block'),
    'custom settings' => FALSE,
  );

}

